export declare const ErrorCode: {
    readonly AUTH_REQUIRED: "AUTH_REQUIRED";
    readonly AUTH_INVALID: "AUTH_INVALID";
    readonly AUTH_EXPIRED: "AUTH_EXPIRED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly USER_NOT_FOUND: "USER_NOT_FOUND";
    readonly VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND";
    readonly STATION_NOT_FOUND: "STATION_NOT_FOUND";
    readonly TRIP_NOT_FOUND: "TRIP_NOT_FOUND";
    readonly BATTERY_SERVICE_UNAVAILABLE: "BATTERY_SERVICE_UNAVAILABLE";
    readonly ROUTING_SERVICE_UNAVAILABLE: "ROUTING_SERVICE_UNAVAILABLE";
    readonly PREDICTION_SERVICE_UNAVAILABLE: "PREDICTION_SERVICE_UNAVAILABLE";
    readonly OPTIMIZER_SERVICE_UNAVAILABLE: "OPTIMIZER_SERVICE_UNAVAILABLE";
    readonly ROUTE_UNAVAILABLE: "ROUTE_UNAVAILABLE";
    readonly INSUFFICIENT_BATTERY: "INSUFFICIENT_BATTERY";
    readonly VALIDATION_ERROR: "VALIDATION_ERROR";
    readonly RATE_LIMITED: "RATE_LIMITED";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
};
export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
//# sourceMappingURL=errors.d.ts.map